name: ipy3
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- markupsafe=0.23=py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.0=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5=py35_0
- pygments=2.1.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python.app=1.2=py35_4
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - gnureadline==6.3.3
  - ipython-genutils==0.1.0
  - isodate==0.5.4
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - pyparsing==2.1.4
  - rdflib==4.2.1
  - scikit-learn==0.17.1
  - scipy==0.16.1
  - sklearn==0.0
  - widgetsnbextension==1.2.2

name: ipy3
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- markupsafe=0.23=py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.0=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5=py35_0
- pygments=2.1.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python.app=1.2=py35_4
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - cycler==0.10.0
  - gnureadline==6.3.3
  - ipython-genutils==0.1.0
  - isodate==0.5.4
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - lasagne==0.1
  - matplotlib==2.0.0b3
  - pandas==0.18.1
  - pyparsing==2.1.4
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - rdflib==4.2.1
  - scikit-learn==0.17.1
  - scikit-neuralnetwork==0.7
  - scipy==0.16.1
  - seaborn==0.7.1
  - six==1.10.0
  - sklearn==0.0
  - theano==0.8.2
  - widgetsnbextension==1.2.2

